# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 620f32882e01ba2aed4ebaf5eea15be1acde7767e85b99ed295bfe6f6d5b9e20232675f4aa18b90ef074c623d96ac2b8611ea02ef2ef9a118b4909b018c301d9

test:
  secret_key_base: c2065c7d19dfd1b777ae76a56c0e2f0fd64dbb39490063481210d9b7391b209699ef7f12ba55b880f36b5e9bc67ac31cf2f67cf524c503c35f25c85c83e56a22

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
